on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: docker.io
  IMAGE_NAME: dockerscoutpolicy/pnorton-consumer
  REF_TAG: ${{ github.event.pull_request.head.sha || github.event.after }}
  PUSH_TAG: latest

jobs:
  build-push-compare:
    runs-on: ubuntu-latest
    name: Docker Scout Compare

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: paulnorton311
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/build-push-action@v5
        if: ${{ github.event_name == 'pull_request' }}
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.REF_TAG }}

      - uses: pnorton5432/scout-action@testing
        if: ${{ github.event_name == 'pull_request' }}
        with:
          command: compare
          image: ${{ env.IMAGE_NAME }}:${{ env.REF_TAG }}
          to: dockerscoutpolicy/analysis-disabled:latest
          github-token: ${{ secrets.PR_PAT }}

      - uses: docker/build-push-action@v5
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.PUSH_TAG }}
